language: go

go:
  - "1.11"

env:
  - GO111MODULE=on

jobs:
  include:
    - stage: "test"
      name: "build"
      script:
        - make build-linux
        - docker build -t moiot/gravity-operator:${TRAVIS_COMMIT::8} -f Dockerfile.operator .
        - docker build -t moiot/gravity-gatekeeper:${TRAVIS_COMMIT::8} -f Dockerfile.gatekeeper .
    - name: "test"
      script: make test
      after_script: make test-down
    - stage: "publish"
      if: tag IS present
      script:
        - make build-linux
        - docker build -t moiot/gravity-operator:${TRAVIS_TAG} -f Dockerfile.operator .
        - docker build -t moiot/gravity-gatekeeper:${TRAVIS_TAG} -f Dockerfile.gatekeeper .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push moiot/gravity-operator:${TRAVIS_TAG}
        - docker push moiot/gravity-gatekeeper:${TRAVIS_TAG}