apiVersion: v1
kind: Service
metadata:
  name: gravity
  labels:
    app.kubernetes.io/name: gravity
    helm.sh/chart: {{ include "gravity-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: http
      port: {{ .Values.gravity.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: gravity