---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gravity-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gravity-operator.name" . }}
    helm.sh/chart: {{ include "gravity-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.operator.service.type }}
  ports:
    - name: http
      port: {{ .Values.operator.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "gravity-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gravity-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gravity-operator.name" . }}
    helm.sh/chart: {{ include "gravity-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gravity-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gravity-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "gravity-operator.fullname" . }}
      restartPolicy: Always
      containers:
        - name: operator
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          command: ["/gravity-operator"]
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          {{- if .Values.operator.resources }}
          resources:
  {{ toYaml .Values.operator.resources | indent 10 }}
  {{- end }}